#!/usr/bin/env bash

count=0

ID="$(ip link | awk '/state UP/ {print $2}')"
SSID="$(iwgetid -r)"

net_stat () {
	if (ping -c 1 8.8.8.8) &>/dev/null; then
		if [[ $ID == e* ]]; then
			echo "Online"
			echo ""
		else
			echo "$SSID"
			echo ""
		fi
	else
		echo "Offline"
		echo ""	
	fi
}

if [[ $1 == '--stat' ]]; then
	net_stat | head -n1
elif [[ $1 == '--icon' ]]; then
	net_stat | tail -n1
fi
